# Generated by Django 4.2.6 on 2023-12-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='default Status', max_length=200, null=True),
        ),
    ]
